spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kticket_db
    username: kticket_user
    password: kticket_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # or create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect