version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kticket-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kticket_db
      POSTGRES_USER: kticket_user
      POSTGRES_PASSWORD: kticket_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: